// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWnNd33WkvqO4iX_44TcpcZBnEJiSl6U',
    appId: '1:121736991733:android:a27a4d09a3fca5672346bc',
    messagingSenderId: '121736991733',
    projectId: 'shoppingapp-3e213',
    storageBucket: 'shoppingapp-3e213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppimtKzCXBMMc2wCDxUcwdvCWrKlMZew',
    appId: '1:121736991733:ios:f886548dd6b87eb42346bc',
    messagingSenderId: '121736991733',
    projectId: 'shoppingapp-3e213',
    storageBucket: 'shoppingapp-3e213.firebasestorage.app',
    androidClientId: '121736991733-aftngn5cfa6iic2r5k2h4c4fromu5giu.apps.googleusercontent.com',
    iosClientId: '121736991733-a82mees2v4r545uv0sl1iiv1ir70pssm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}